// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:4bb220f1-d723-4ce7-ba3a-4178ac27f5e5',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'trendr-hosting-mobilehub-877044095',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd112jjfz0x7ae5.cloudfront.net',
    'aws_mobile_analytics_app_id': '24f1ab781c1242c59a83ff960520ae64',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a88ecd88-30d5-4265-b232-ba0443de391d',
    'aws_project_name': 'Trendr',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'trendr-mobilehub-877044095',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_AlIl87wxR',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '5rsig7thpkt5s0k3qfg08o0msr',
}

export default awsmobile;
